/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT hello.cdb */

/*  Include Header Files  */
#include <std.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sem.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern far HST_Obj RTA_fromHost;
extern far HST_Obj RTA_toHost;
extern far SWI_Obj KNL_swi;
extern far TSK_Obj TSK_idle;
extern far TSK_Obj TSK_mute;
extern far TSK_Obj TSK_loopback;
extern far TSK_Obj TSK_process;
extern far TSK_Obj TSK_printstat;
extern far LOG_Obj LOG_system;
extern far LOG_Obj trace;
extern far SEM_Obj SEM_rcv;
extern far SEM_Obj SEM_xmt;
extern far STS_Obj IDL_busyObj;
extern far STS_Obj STS_left;
extern far STS_Obj STS_right;


#ifdef __cplusplus
}
#endif /* extern "C" */
